config/routes.rb
Rails.application.routes.draw do
  root "users/homes#top"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
  }

  get 'homes/top'

  scope module: :users do
    resources :users, only: [:show, :edit, :update] do
      collection do
        get "quit"
        put "out"
        get "search"
      end
      member do
        get "followings"
        get "followers"
      end
    end

    resources :posts do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end

    resources :follow_relationships, only: [:create, :destroy] do

    end
    resources :rooms, only: [:index, :show, :create, :destroy]
  end

  namespace :admins do
    resources :posts, only: [:index, :show, :destroy]
    resources :users, only: [:index, :show, :edit, :update]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_images, dependent: :destroy
  accepts_attachments_for :post_images, attachment: :post_image

  validates :body, length: { in: 1..140 }
  with_options numericality: { only_integer: true }, allow_blank: true do
    validates :AB
    validates :single
    validates :double
    validates :triple
    validates :HR
    validates :RBI
    validates :run
    validates :BB_HBP
    validates :steal
    validates :inning
    validates :hit_allowed
    validates :run_allowed
    validates :SO
    validates :BB_HBP_allowed
    validates :score_my_team
    validates :score_team_against
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  enum win_lose: { win: 0, draw: 1, lose: 2 }

  def Post.search(search, search_option)
    if search_option == "2"
      Post.where(['body LIKE ?', "%#{search}%"])
    end
  end

end

app/controllers/admins/posts_controller.rb
class Admins::PostsController < ApplicationController
  before_action :authenticate_admins!

  def index
    @posts = Post.page(params[:page]).per(5).order(id: "DESC")
    @post_count = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @post_images = Post.find(params[:id]).post_images
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admins_posts_path
  end

end

app/controllers/users/posts_controller.rb
class Users::PostsController < ApplicationController
  before_action :authenticate_user!

  def new
    @post = Post.new
    @post.post_images.build
  end

  def index
    @posts = Post.page(params[:page]).per(5).order(id: "DESC")
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @user = current_user
    @post_images = Post.find(params[:id]).post_images
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    # YoutubeURLの埋め込み
    url = params[:post][:youtube_url]
    url = url.last(11)
    @post.youtube_url = url
    # ここまで

    if @post.save
      redirect_to posts_path, notice: "投稿に成功しました。"
    else
      render "new"
    end
  end

  def edit
    @user = current_user
    @post = Post.find(params[:id])
    if @post.user == current_user
      render "edit"
    else
      redirect_to posts_path
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to posts_path
    else
      render "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:AB, :single, :double, :triple, :HR, :RBI, :run, :BB_HBP, :steal,
                                 :inning, :hit_allowed, :run_allowed, :SO, :BB_HBP_allowed, :body, :youtube_url,
                                 :team_against, :score_my_team, :score_team_against, :date, :win_lose, post_images_post_images: [])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admins/posts/index.html.erb
<div class="container-fluid">
  <div class="row">

    <div class="col-10 offset-1 mt-5" id="main">

      <% if flash[:notice] %>
        <div class="alert alert-success" role="alert">
          <%= notice %>
        </div>
      <% end %>

      <h5 class="mb-5">
        総投稿数：<%= @post_count.count %>
      </h5>

      <div class="jscroll posts">
        <% @posts.each do |post| %>
          <div class="card mb-4">
            <div class="card-body">
              <%= link_to user_path(post.user) do %>
                <div class="row align-items-center">
                  <%= attachment_image_tag(post.user, :profile_image, fallback: "no-image.png", size: "50x50") %>
                  <h5><%= post.user.name %></h5>
                </div>
              <% end %>
              <p class="card-text">
                <small class="text-muted"><%= post.created_at.strftime('%Y/%m/%-d/%R') %></small>
              </p>
              <p class="card-text">
                <%= simple_format(post.body) %>
              </p>
              <div class="row align-items-center">
                <div class="far fa-comment col-3 text-center"><%= post.post_comments.count %></div>
                <div class="far col-3 text-center fa-heart"><%= post.favorites.count %></div>
                <div class="col-3 text-center"><%= link_to "詳細", admins_post_path(post), class: "btn btn-outline-primary" %></div>
                <% if admin_signed_in? %>
                  <div class="col-3 text-center"><%= link_to "削除", admins_post_path(post), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn btn-outline-danger" %></div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
        <%= paginate @posts %>
      </div>
    </div>


  </div>
</div>

app/views/admins/posts/show.html.erb
<div class="container-fluid">
  <div class="row">

    <div class="col-10 offset-1 mt-5" id="main">

      <div class="card mb-4">
        <div class="card-body">
          <%= link_to user_path(@post.user) do %>
            <div class="row align-items-center">
              <%= attachment_image_tag(@post.user, :profile_image, fallback: "no-image.png", size: "70x70") %>
              <h5><%= @post.user.name %></h5>
            </div>
          <% end %>
          <p class="card-text">
            <small class="text-muted"><%= @post.created_at.strftime('%Y/%m/%-d/%R') %></small>
          </p>
          <p class="card-text">
            <%= simple_format(@post.body) %>
          </p>

          <% if admin_signed_in? %>
    			  <div class="row align-items-center">
              <div class="far fa-comment col-4 text-center"><%= @post.post_comments.count %></div>
              <div class="far col-4 text-center fa-heart"><%= @post.favorites.count %></div>
              <div class="col-4 text-center"><%= link_to "削除", admins_post_path(@post), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn btn-outline-danger" %></div>
            </div>
      		<% end %>
        </div>
      </div>

      <h3>成績</h3>
    	<div class="accordion" id="accordionExample">
        <div class="card">
          <div class="card-header" id="headingOne">
            <h5 class="mb-0">
              <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                打撃
              </button>
            </h5>
          </div>

          <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
            <div class="card-body">
              <table class="table table-bordered table-condensed">
                <tr>
                  <th>打数</th>
                  <th>単打</th>
                  <th>二塁打</th>
                  <th>三塁打</th>
                  <th>本塁打</th>
                  <th>打点</th>
                  <th>得点</th>
                  <th>四死球</th>
                  <th>盗塁</th>
                </tr>
                <tr>
                  <td><%= @post.AB %></td>
                  <td><%= @post.single %></td>
                  <td><%= @post.double %></td>
                  <td><%= @post.triple %></td>
                  <td><%= @post.HR %></td>
                  <td><%= @post.RBI %></td>
                  <td><%= @post.run %></td>
                  <td><%= @post.BB_HBP %></td>
                  <td><%= @post.steal %></td>
                </tr>
              </table>
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-header" id="headingTwo">
            <h5 class="mb-0">
              <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                投球
              </button>
            </h5>
          </div>
          <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
            <div class="card-body">
              <table class="table table-bordered table-condensed">
                <tr>
                  <th>投球回</th>
                  <th>被安打</th>
                  <th>失点</th>
                  <th>奪三振</th>
                  <th>与四死球</th>
                </tr>
                <tr>
                  <td><%= @post.inning %></td>
                  <td><%= @post.hit_allowed %></td>
                  <td><%= @post.run_allowed %></td>
                  <td><%= @post.SO %></td>
                  <td><%= @post.BB_HBP_allowed %></td>
                </tr>
              </table>
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-header" id="headingThree">
            <h5 class="mb-0">
              <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                チーム
              </button>
            </h5>
          </div>
          <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
            <div class="card-body">
              <table class="table table-bordered table-condensed">
                <tr>
                  <th>対戦チーム</th>
                  <th>得点</th>
                  <th>失点</th>
                  <th>試合日</th>
                </tr>
                <tr>
                  <td><%= @post.team_against %></td>
                  <td><%= @post.score_my_team %></td>
                  <td><%= @post.score_team_against %></td>
                  <td><%= @post.date %></td>
                </tr>
              </table>
            </div>
          </div>
        </div>
      </div>
      <div id="carouselExampleIndicators" class="carousel slide my-5" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <% @post_images.drop(1).count.times do |index| %>
            <li data-target="#carouselExampleIndicators" data-slide-to="#{index}"></li>
          <% end %>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <% @post_images.first(1).each do |post_image| %>
              <%= attachment_image_tag post_image, :post_image, class: "carousel_image col-12" %>
            <% end %>
          </div>
          <% @post_images.drop(1).each do |post_image| %>
            <div class="carousel-item">
              <%= attachment_image_tag post_image, :post_image, class: "carousel_image col-12" %>
            </div>
          <% end %>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

      <% if @post.youtube_url.present? %>
        <div class="youtube mt-5">
          <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @post.youtube_url%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
      <% end %>

		</div>
  </div>
</div>